### ISSUE TITLE
It would be better to illustrate that this could only be used in Node.js

### ISSUE THREAD

**Issue by jasonxia23** [sindresorhus/sleep-synchronously#1]
Since modern browsers support `Atomics.wait` may not allow to use `Atomics.wait` in main thread, it will throw error if anyone try to use this package in browsers.

**Comment by sindresorhus** [comment]
What browsers? Did you test that it doesn't work?

**Comment by jasonxia23** [comment]
I tested it in Chrome, `TypeError` thrown like this:
```
Uncaught TypeError: Atomics.wait cannot be called in this context
```
